#!/usr/bin/env python3
"""Give every published notebook its own `description:` for search results.

Without one, all 27 notebook pages inherit the site-wide description, so search
engines see 27 pages with identical snippets and social shares all read the same.

The description is not invented here: it is taken from the notebook's own opening
tagline — the paragraph the author already wrote under the H1 — with markdown
stripped. Quarto reads YAML from a leading *raw* cell in a .ipynb, so that is
where it goes; no existing cell is touched.

    python tools/add_notebook_descriptions.py --check    # report, change nothing
    python tools/add_notebook_descriptions.py            # write

Re-running is safe: an existing generated raw cell is replaced, not stacked.
"""
from __future__ import annotations

import argparse
import glob
import io
import json
import re
import sys

MARKER = "# generated by tools/add_notebook_descriptions.py"
MAX_LEN = 300
DIRS = ("ML-Zero-to-Hero", "DSA-Zero-to-Hero")

# "**NB-08 in the [DSA: Zero to Hero](README.md) series.**" is a series pointer,
# not a tagline - skip it and take the paragraph after.
SERIES_MARKER = re.compile(r"^\*\*NB-\d+ in the .*series\.\*\*$", re.S)

# Some openings lead with where the notebook came from, or how to read it. Neither
# describes the subject, and the provenance one links to an unpublished tracker.
SKIP_PARAGRAPH = (
    re.compile(r"extracted and expanded from", re.I),
    re.compile(r"^\*\*How to use it:\*\*", re.I),
)

# "**Who this is for:** someone who..." is a real description wearing a label.
WHO_FOR = re.compile(r"^\*\*Who this is for:\*\*\s*", re.I)


def strip_markdown(text: str) -> str:
    text = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", text)   # links -> label
    text = re.sub(r"`([^`]*)`", r"\1", text)               # inline code
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)         # bold
    text = re.sub(r"(?<!\w)\*([^*]+)\*(?!\w)", r"\1", text)  # italics
    text = text.replace("— ", "— ")
    return re.sub(r"\s+", " ", text).strip()


def extract_description(nb: dict) -> str | None:
    """The opening tagline, as prose."""
    cells = [c for c in nb["cells"] if c["cell_type"] == "markdown"]
    if not cells:
        return None
    src = "".join(cells[0]["source"])
    lines = src.split("\n")
    if not lines or not lines[0].startswith("# "):
        return None

    paragraphs, current = [], []
    for line in lines[1:]:
        s = line.strip()
        # Stop at the first blockquote, horizontal rule or subheading.
        if s.startswith((">", "***", "---", "##")):
            break
        if not s:
            if current:
                paragraphs.append(" ".join(current))
                current = []
            continue
        current.append(s)
    if current:
        paragraphs.append(" ".join(current))

    kept = []
    for p in paragraphs:
        p = p.strip()
        if SERIES_MARKER.match(p) or any(r.search(p) for r in SKIP_PARAGRAPH):
            continue
        if WHO_FOR.match(p):
            p = "For " + WHO_FOR.sub("", p)
        kept.append(p)
    paragraphs = kept
    if not paragraphs:
        return None

    out = ""
    for p in paragraphs:
        candidate = (out + " " + strip_markdown(p)).strip()
        if out and len(candidate) > MAX_LEN:
            break
        out = candidate
        if len(out) >= 120:
            break

    if len(out) > MAX_LEN:                      # trim on a word boundary
        out = out[:MAX_LEN].rsplit(" ", 1)[0].rstrip(" ,;:—-") + "…"
    return out or None


def raw_cell(description: str) -> dict:
    body = "\n".join("  " + ln for ln in description.split("\n"))
    text = "---\ndescription: |\n%s\n---\n\n%s\n" % (body, MARKER)
    # nbformat 4.5 requires every cell to carry a unique id.
    return {"cell_type": "raw", "id": "quarto-frontmatter",
            "metadata": {"raw_mimetype": "text/restructuredtext"},
            "source": text.splitlines(keepends=True)}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only")
    args = ap.parse_args()

    files = sorted(f for d in DIRS for f in glob.glob("%s/*.ipynb" % d))
    problems, written = [], 0

    for path in files:
        raw = io.open(path, "r", encoding="utf-8", newline="").read()
        crlf = "\r\n" in raw
        nb = json.loads(raw)

        existing = nb["cells"] and nb["cells"][0]["cell_type"] == "raw" \
            and MARKER in "".join(nb["cells"][0]["source"])
        body = nb["cells"][1:] if existing else nb["cells"]
        desc = extract_description({"cells": body})

        if not desc:
            problems.append(path)
            print("  SKIP  %-58s no tagline found" % path)
            continue
        print("  %-58s %s" % (path.replace("\\", "/"), desc[:96]))

        if args.check:
            continue
        nb["cells"] = [raw_cell(desc)] + body
        out = json.dumps(nb, indent=1, ensure_ascii=False)
        if not out.endswith("\n"):
            out += "\n"
        if crlf:
            out = out.replace("\n", "\r\n")
        io.open(path, "w", encoding="utf-8", newline="").write(out)
        written += 1

    print("\n%d notebooks, %d described, %d without a usable tagline"
          % (len(files), len(files) - len(problems), len(problems)))
    if not args.check:
        print("%d written" % written)
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
